In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
machine_labor = pd.DataFrame({'Mach hrs': [68,88,62,72,60,96,78,46,82, 94, 68, 48],
                             'Ind Labor': [1190,1211, 1004, 917, 770, 1456, 1180, 710, 1316, 1032, 752, 963]})
print (machine_labor)

    Mach hrs  Ind Labor
0         68       1190
1         88       1211
2         62       1004
3         72        917
4         60        770
5         96       1456
6         78       1180
7         46        710
8         82       1316
9         94       1032
10        68        752
11        48        963


In [5]:
machine_labor = machine_labor.rename(columns = {'A': 'B'})
print (machine_labor)

    Mach hrs  Ind Labor
0         68       1190
1         88       1211
2         62       1004
3         72        917
4         60        770
5         96       1456
6         78       1180
7         46        710
8         82       1316
9         94       1032
10        68        752
11        48        963


In [6]:
machine_labor.columns = ['A0', 'B0']
print (machine_labor)

    A0    B0
0   68  1190
1   88  1211
2   62  1004
3   72   917
4   60   770
5   96  1456
6   78  1180
7   46   710
8   82  1316
9   94  1032
10  68   752
11  48   963


In [13]:
from sklearn import linear_model
lm = linear_model.LinearRegression()
X = machine_labor.loc[:, ['A0']]
print (X)

Y = machine_labor.B0
lm.fit(X, Y)
print (lm.coef_, lm.intercept_)

    A0
0   68
1   88
2   62
3   72
4   60
5   96
6   78
7   46
8   82
9   94
10  68
11  48
[10.31239512] 300.9762837006376


In [8]:
print (lm)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)


In [9]:
### Goodness of fit
R2 = lm.score(X,Y)
print (R2)

0.5214333283443293


In [10]:
from sklearn.metrics import mean_squared_error
Y_predict = lm.predict(X)
mse = mean_squared_error(Y_predict, Y)
print (mse)
mse = mean_squared_error(Y, Y_predict)
print (mse)
print (np.sqrt(mse))

24235.34407278964
24235.34407278964
155.67705056555266


In [1]:
machine_labor["A1"] = [18, 28, 19, 15, 25, 30, 19, 22, 27, 21, 26, 29]
from scipy.stats import linregress
print (X)
print (X.shape)
#  X= np.array(machine_labor.loc [:, ["A0", "A1"]]) [:, 0:2]
                                   
# X= np.array(machine_labor.loc [:, ["A0", "A1"]])
X = np.append([X[:, 0]], [X[:, 1]], axis=0)
print (X)

# X = np.append([X[:, 0]], [X[:, 1]], axis=0)
# print (X)

Y = np.array(Y)
print (Y)

print (linregress(X, Y))
# slope, intercept, r_value, p_value, std_err = linregress(X, Y)
# print (slope, intercept, r_value, p_value, std_err)

In [22]:
print (np.append([X[:, 0]], [X[:, 1]], axis=0))

[[68 88 62 72 60 96 78 46 82 94 68 48]
 [18 28 19 15 25 30 19 22 27 21 26 29]]


In [35]:
# Convert the data into a Pandas DataFrame to use the formulas framework
# in statsmodels

# For statistics. Requires statsmodels 5.0 or more
from statsmodels.formula.api import ols
# Analysis of Variance (ANOVA) on linear models
from statsmodels.stats.anova import anova_lm

# Fit the model
model = ols("B0 ~ A0 + A1", machine_labor).fit()

# Print the summary
print(model.summary())

print("\nRetrieving manually the parameter estimates:")
print(model._results.params)
# should be array([-4.99754526,  3.00250049, -0.50514907])

# Peform analysis of variance on fitted linear model
anova_results = anova_lm(model)

print('\nANOVA results')
print(anova_results)

plt.show()


                            OLS Regression Results                            
Dep. Variable:                     B0   R-squared:                       0.543
Model:                            OLS   Adj. R-squared:                  0.442
Method:                 Least Squares   F-statistic:                     5.356
Date:                Fri, 05 Jul 2019   Prob (F-statistic):             0.0294
Time:                        17:38:27   Log-Likelihood:                -77.319
No. Observations:                  12   AIC:                             160.6
Df Residuals:                       9   BIC:                             162.1
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    155.9005    323.349      0.482      0.6

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\scipy\stats\stats.py:1394: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=12
  "anyway, n=%i" % int(n))


In [10]:
df = pd.DataFrame(np.arange(12).reshape(3, 4),  columns=['A', 'B', 'C', 'D'])
print (df.iloc[2,:])

A     8
B     9
C    10
D    11
Name: 2, dtype: int32


In [12]:
x = np.arange(12)
print (x)

y = np.split(x, 3)
print (y)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
