In [1]:
import numpy as np
from sklearn.decomposition import PCA
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
pca = PCA(n_components=2)
pca.fit(X)  
print(pca.explained_variance_ratio_)  

[0.99244289 0.00755711]


In [2]:
X = np.array([[-1, -1, 3], [-2, -1, 1], [-3, -2, 4], [1, 1, 5], [2, 1, 0], [3, 2, 9]])
pca = PCA(n_components=3)
pca.fit(X)  
print(pca.explained_variance_ratio_)
print (np.sum(pca.explained_variance_ratio_))
print (pca.components_)
print (pca.explained_variance_)

[0.71154703 0.28542845 0.00302452]
1.0
[[ 0.48912325  0.33346615  0.80595209]
 [ 0.68893247  0.41898205 -0.59146098]
 [ 0.53491168 -0.84454388  0.0248018 ]]
[12.99759236  5.21382634  0.05524798]


In [3]:
print (0.71154703/0.28542845, 12.9975923612/5.21382634)

2.4929085730592027 2.4929085691795407


In [4]:
pca = PCA(n_components=2)
pca.fit(X)  
print(pca.explained_variance_ratio_)
print (np.sum(pca.explained_variance_ratio_))
print (pca.components_)
print (pca.explained_variance_)

[0.71154703 0.28542845]
0.9969754758062892
[[ 0.48912325  0.33346615  0.80595209]
 [ 0.68893247  0.41898205 -0.59146098]]
[12.99759236  5.21382634]
